- include: ../docker_common.yml

- name: Set max install version on SUSE
  set_fact:
    replicated_docker_version: 1.10.3
  when:
    - ansible_distribution_major_version == "12"

- include: ../docker_service.yml
