###
### Automation Setup
###
### Parameters are:
###   - replicated_automation_settings_file
###   - replicated_automation_conf_file
###   - replicated_automation_extra_files
###

- name: d1
  debug:
    msg: "Private ip is {{ replicated_private_address }}"

- name: Check if settings file should be copied
  local_action: stat path='{{replicated_automation_settings_file}}'
  register: settings
  when: replicated_automation_settings_file is defined

- name: Copy settings file
  copy:
    dest: "/etc/settings.conf"
    src: '{{replicated_automation_settings_file}}'
    owner: root
    group: root
    mode: "ugo=r"
  when:
  - replicated_automation_settings_file is defined
  - settings.stat.exists
  no_log: false
  become: yes
  become_method: sudo

- name: Check if replicated conf file should be copied
  local_action: stat path='{{replicated_automation_conf_file}}'
  register: conf_file
  when: replicated_automation_conf_file is defined

- name: Copy Replicated config file
  copy:
    dest: "/etc/replicated.conf"
    src: '{{replicated_automation_conf_file}}'
    owner: root
    group: root
    mode: "ugo=r"
  when:
  - replicated_automation_conf_file is defined
  - conf_file.stat.exists
  no_log: false
  become: yes
  become_method: sudo

- name: Copy extra files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ replicated_automation_extra_files }}"
  when: replicated_automation_extra_files is defined

###
### Install Replicated
###
### Parameters are:
###   - replicated_private_address
###   - replicated_public_address
###   - replicated_proxy
###   - replicated_docker_version
###   - replicated_install replicated|operator; replicated is the default
###

###
### Run the docker install for the operating system
###

- name: Check if Docker is already installed
  stat:
    path: /usr/bin/dockerd
  register: docker_installed

- name: Install Docker
  include: docker/pre/{{ ansible_distribution }}.yml
  when: docker_installed.stat.exists == False

###
### Install Replicated
###

- name: Installing Replicated Containers
  include: scheduler/replicated/replicated.yml
  when: replicated_install is not defined or replicated_install == "replicated"

###
### Install Replicated Operator
###

- name: Prep operator install env vars
  set_fact:
    replicated_daemon_endpoint: '{{ ansible_default_ipv4.address }}:9879'
    replicated_daemon_host: '{{ ansible_default_ipv4.address }}'

- name: Installing Replicated-Operator
  include: scheduler/replicated/operator.yml
  when: replicated_install is not defined or replicated_install == "operator" or replicated_install == "replicated"

