###
### Automation Setup
###
### Parameters are:
###   - automation_replicated_setting
###   - automation_replicated_conf
###   - automation_extra_files
###

- name: Check if settings file should be copied
  local_action: stat path='{{automation_replicated_setting}}'
  register: settings
  when: automation_replicated_setting is defined

- name: Copy settings file
  copy:
    dest: "/etc/settings.conf"
    src: '{{automation_replicated_setting}}'
    owner: root
    group: root
    mode: "ugo=r"
  when:
  - automation_replicated_setting is defined
  - settings.stat.exists
  no_log: false
  become: yes
  become_method: sudo

- name: Check if replicated conf file should be copied
  local_action: stat path='{{automation_replicated_conf}}'
  register: conf_file
  when: automation_replicated_conf is defined

- name: Copy Replicated config file
  copy:
    dest: "/etc/replicated.conf"
    src: '{{automation_replicated_conf}}'
    owner: root
    group: root
    mode: "ugo=r"
  when:
  - automation_replicated_conf is defined
  - conf_file.stat.exists
  no_log: false
  become: yes
  become_method: sudo

- name: Copy extra files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ automation_extra_files }}"
  when: automation_extra_files is defined

###
### Install Replicated
###
### Parameters are:
###   - private_address
###   - public_address
###   - proxy
###   - docker_version
###   - install replicated|operator; replicated is the default
###

- name: Set install parameters
  set_fact:
    opt_private_address: '{{ private_address | default(ansible_default_ipv4.address) }}'
    opt_public_address: '{{ public_address | default(ansible_default_ipv4.address) }}'
    opt_proxy: '{{ proxy | default("no-proxy") }}'
    opt_install: '{{ install | default("replicated") }}'

- name: Set docker version
  set_fact:
    opt_docker_version: 'docker-version={{ docker_version }}'
  when: docker_version is defined

- name: Default docker version if not passed
  set_fact:
    opt_docker_version: ''
  when: opt_docker_version is not defined

###
### Run the docker install for the operating system
###

- name: Check if Docker is already installed
  stat:
    path: /usr/bin/dockerd
  register: docker_installed

- name: Install Docker
  include: os/{{ ansible_distribution }}.yml
  when:
  - docker_installed is not defined
  - not replicated_skip_docker_install

###
### Install Replicated
###

- name: Installing Replicated Containers
  include: replicated-native/replicated.yml
  when: opt_install is not defined or opt_install == "replicated"

###
### Install Replicated Operator
###

- name: Prep operator install env vars
  set_fact:
    replicated_daemon_endpoint: '{{ ansible_default_ipv4.address }}:9879'
    replicated_daemon_host: '{{ ansible_default_ipv4.address }}'

- name: Installing Replicated-Operator
  include: replicated-native/operator.yml
  when: opt_install is not defined or opt_install == "operator" or opt_install == "replicated"

